<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT7DWxFm\App_KernelProvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT7DWxFm/App_KernelProvDebugContainer.php') {
    touch(__DIR__.'/ContainerT7DWxFm.legacy');

    return;
}

if (!\class_exists(App_KernelProvDebugContainer::class, false)) {
    \class_alias(\ContainerT7DWxFm\App_KernelProvDebugContainer::class, App_KernelProvDebugContainer::class, false);
}

return new \ContainerT7DWxFm\App_KernelProvDebugContainer([
    'container.build_hash' => 'T7DWxFm',
    'container.build_id' => 'a210b9fc',
    'container.build_time' => 1625070880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT7DWxFm');
