<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLbxzzx8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLbxzzx8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLbxzzx8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLbxzzx8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLbxzzx8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lbxzzx8',
    'container.build_id' => '31bf7348',
    'container.build_time' => 1625297910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLbxzzx8');
